@dev_server=http://127.0.0.1:8080

### ai chat
POST {{dev_server}}/v1/chat/completions
Accept: application/json
Content-Type: application/json

{
    "model": "local",
    "stream": false,
    "messages": [
        {"role": "system", "content": "You are helpful."},
        {"role": "user", "content": "Introduce yourself. 1000 words."}
    ],
    "max_tokens": 128,
    "temperature": 0.2,
    "stream_options": {"include_usage": true}
}
